### ISSUE TITLE
compare it with other libraries

### ISSUE THREAD

**Issue by glacierck** [nppoly/cyac#23]
[marisa-trie](https://github.com/pytries/marisa-trie)
[datrie](https://github.com/pytries/datrie)

The above two projects are currently excellent projects. Can people who have used them help evaluate their direct differences？

**Comment by chenkovsky** [comment]
this library is based on cedar trie. 
for performance and trie size, author of cedar trie has compared other tries. please look at http://www.tkl.iis.u-tokyo.ac.jp/~ynaga/cedar/#perf . 
the most important features of this library are 
1. it handles case insensitive match correctly.
  please take care that: 
  ```python
  len(u"İstanbul") != len(u"İstanbul".lower()) 
  ```
2. it supports python memory buffer protocol. https://docs.python.org/3/c-api/buffer.html . it's memory friendly for multi process program.
