### ISSUE TITLE
Error import cyac in shared_buffered branch

### ISSUE THREAD

**Issue by OblackatO** [nppoly/cyac#4]
Hello, 

I would like to run some memory analysis and tests using the new shared_buffer branch. I would post those memory analysis in an issue, so that you could put them in the README.md if you like. 

How I am facing the following problem: 
```
>>> import cyac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/cyac-1.0-py3.7-linux-x86_64.egg/cyac/__init__.py", line 2, in <module>
    from .ac import AC
  File "lib/cyac/ac.pyx", line 1, in init cyac.ac
    #cython: language_level=3, boundscheck=False, overflowcheck=False
  File "lib/cyac/trie.pyx", line 1, in init cyac.trie
    #cython: language_level=3, boundscheck=False, overflowcheck=False
ModuleNotFoundError: No module named 'cyac.util'
```
**What I did to install it:** 
- I cloned the cyac rep
- git checkout shared_buffer
- python3.7 setup.py build
- python3.7 setup.py install
- and then imported cyac and the error occurred.

Tried with python3.7 and 3.6.

**Comment by nppoly** [comment]
i havent finished it yet, i will tell you after implementation and test.

**Comment by OblackatO** [comment]
ah ok. I am sorry. :( I saw the description on the README.md file and thought it was ready to use.
